add rails controller testing
X-Elie-X/Blog-app pull request #7
Opened 2022-12-13 14:00 UTC by X-Elie-X

### in this PR I implemented the following:
- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:
If the response status was correct.
If a correct template was rendered.
If the response body includes the correct placeholder text.

2022-12-13 14:31 UTC, gemmen29 requested changes
Hi @X-Elie-X, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 14:31 UTC, gemmen29 commented on spec/Request/posts_specs.rb
> +require 'rails_helper'
- [ ] Kindly rename the file from `posts_specs.rb` to `posts_spec.rb` as this is the naming convention for test files in order to run tests inside that file.

2022-12-13 14:31 UTC, gemmen29 commented on spec/Request/user_specs.rb
> +
- [ ] Kindly rename the file from `user_specs.rb` to `user_spec.rb` as this is the naming convention for test files in order to run tests inside that file.

2022-12-13 14:31 UTC, gemmen29 commented on spec/Request/user_specs.rb
> +RSpec.describe 'Users', type: :request do
- [ ] Kindly fix the failed test cases
![image](https://user-images.githubusercontent.com/24703171/207360537-916b0b18-7efd-4af4-9f47-e1dfeaac0da2.png)

2022-12-14 13:57 UTC, OLIPLICHE approved these changes
Hi @X-Elie-X, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Implement the changes 👏
- Wrote the tests for controllers👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 13:57 UTC, OLIPLICHE commented on spec/Request/user_spec.rb
> +RSpec.describe 'User', type: :request do
- [ ] Congrat 👍 

![Capture](https://user-images.githubusercontent.com/63972670/207613861-33314136-5988-4c2f-955b-d732cad5d69d.JPG)

2022-12-14 14:01 UTC, merged